language: cpp
jobs:
  include:
    # linux
    - name: "ARCH=arm32_v5"
      env: ARCH=arm32_v5
    - name: "ARCH=arm32_v6"
      env: ARCH=arm32_v6
    - name: "ARCH=arm32_v7"
      env: ARCH=arm32_v7
    - name: "ARCH=arm64"
      env: ARCH=arm64
    - name: "ARCH=mips"
      env: ARCH=mips
    - name: "ARCH=mipsel"
      env: ARCH=mipsel
    - name: "ARCH=ppc32"
      env: ARCH=ppc32
    - name: "ARCH=ppc64"
      env: ARCH=ppc64
    - name: "ARCH=ppc64le"
      env: ARCH=ppc64le
    - name: "ARCH=riscv BOOT=0"
      env: ARCH=riscv
    - name: "ARCH=s390 BOOT=0"
      env: ARCH=s390
    - name: "ARCH=x86"
      env: ARCH=x86
    - name: "ARCH=x86_64"
      env: ARCH=x86_64
    - name: "ARCH=arm32_v5 REPO=linux-next"
      env: ARCH=arm32_v5 REPO=linux-next
    - name: "ARCH=arm64 REPO=linux-next"
      env: ARCH=arm64 REPO=linux-next
    - name: "ARCH=x86 REPO=linux-next"
      env: ARCH=x86 REPO=linux-next
    - name: "ARCH=x86_64 REPO=linux-next"
      env: ARCH=x86_64 REPO=linux-next
    # linux (cron only)
    #
    # linux-next (cron only)
    - name: "ARCH=arm32_v5 REPO=linux-next"
      env: ARCH=arm32_v5 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v6 REPO=linux-next"
      env: ARCH=arm32_v6 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=linux-next"
      env: ARCH=arm32_v7 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm64 REPO=linux-next"
      env: ARCH=arm64 REPO=linux-next
      if: type = cron
    - name: "ARCH=mips REPO=linux-next"
      env: ARCH=mips REPO=linux-next
      if: type = cron
    - name: "ARCH=mipsel REPO=linux-next"
      env: ARCH=mipsel REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc32 REPO=linux-next"
      env: ARCH=ppc32 REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc64 REPO=linux-next"
      env: ARCH=ppc64 REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc64le REPO=linux-next"
      env: ARCH=ppc64le REPO=linux-next
      if: type = cron
    - name: "ARCH=riscv REPO=linux-next BOOT=0"
      env: ARCH=riscv REPO=linux-next
      if: type = cron
    - name: "ARCH=s390 BOOT=0 REPO=linux-next"
      env: ARCH=s390 REPO=linux-next
      if: type = cron
    - name: "ARCH=x86 REPO=linux-next"
      env: ARCH=x86 LD=ld.lld REPO=linux-next
      if: type = cron
    - name: "ARCH=x86_64 REPO=linux-next"
      env: ARCH=x86_64 REPO=linux-next
      if: type = cron
    # stable
    - name: "ARCH=arm32_v7 REPO=5.4"
      env: ARCH=arm32_v7 REPO=5.4
      if: type = cron
    - name: "ARCH=arm64 REPO=5.4"
      env: ARCH=arm64 REPO=5.4
      if: type = cron
    - name: "ARCH=mips REPO=5.4"
      env: ARCH=mips REPO=5.4
      if: type = cron
    - name: "ARCH=mipsel REPO=5.4"
      env: ARCH=mipsel REPO=5.4
      if: type = cron
    - name: "ARCH=ppc32 REPO=5.4"
      env: ARCH=ppc32 REPO=5.4
      if: type = cron
    - name: "ARCH=x86_64 REPO=5.4"
      env: ARCH=x86_64 REPO=5.4
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.19"
      env: ARCH=arm32_v7 REPO=4.19
      if: type = cron
    - name: "ARCH=arm64 REPO=4.19"
      env: ARCH=arm64 REPO=4.19
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.19"
      env: ARCH=ppc64le REPO=4.19
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.19"
      env: ARCH=x86_64 REPO=4.19
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.14"
      env: ARCH=arm32_v7 REPO=4.14
      if: type = cron
    - name: "ARCH=arm64 REPO=4.14"
      env: ARCH=arm64 REPO=4.14
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.14"
      env: ARCH=ppc64le REPO=4.14
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.14"
      env: ARCH=x86_64 REPO=4.14
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.9"
      env: ARCH=arm32_v7 REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.9"
      env: ARCH=arm64 REPO=4.9
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.9"
      env: ARCH=x86_64 REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.4"
      env: ARCH=arm64 REPO=4.4
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.4"
      env: ARCH=x86_64 REPO=4.4
      if: type = cron
    # kernel/common
    - name: "ARCH=arm64 REPO=android-4.9-q"
      env: ARCH=arm64 REPO=android-4.9-q
      if: type = cron
    - name: "ARCH=arm64 REPO=android-4.14-stable"
      env: ARCH=arm64 REPO=android-4.14-stable
      if: type = cron
    - name: "ARCH=arm64 REPO=android-4.19"
      env: ARCH=arm64 REPO=android-4.19
      if: type = cron
    - name: "ARCH=arm64 REPO=android-5.4"
      env: ARCH=arm64 REPO=android-5.4
      if: type = cron
    - name: "ARCH=arm64 REPO=android-mainline"
      env: ARCH=arm64 REPO=android-mainline
      if: type = cron
    - name: "ARCH=x86_64 REPO=android-4.9-q"
      env: ARCH=x86_64 REPO=android-4.9-q
      if: type = cron
    - name: "ARCH=x86_64 REPO=android-4.14-stable"
      env: ARCH=x86_64 REPO=android-4.14-stable
      if: type = cron
    - name: "ARCH=x86_64 REPO=android-4.19"
      env: ARCH=x86_64 REPO=android-4.19
      if: type = cron
    - name: "ARCH=x86_64 REPO=android-5.4"
      env: ARCH=x86_64 REPO=android-5.4
      if: type = cron
    - name: "ARCH=x86_64 REPO=android-mainline"
      env: ARCH=x86_64 REPO=android-mainline
      if: type = cron
    # linux with stable LLVM/Clang
    - name: "ARCH=arm32_v5 LLVM_VERSION=10"
      env: ARCH=arm32_v5 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=arm32_v6 LLVM_VERSION=10"
      env: ARCH=arm32_v6 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=arm32_v7 LLVM_VERSION=10"
      env: ARCH=arm32_v7 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=arm64 LLVM_VERSION=10"
      env: ARCH=arm64 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=mips LLVM_VERSION=10"
      env: ARCH=mips LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=mipsel LLVM_VERSION=10"
      env: ARCH=mipsel LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=ppc32 LLVM_VERSION=10"
      env: ARCH=ppc32 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=ppc64 LLVM_VERSION=10"
      env: ARCH=ppc64 LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=ppc64le LLVM_VERSION=10"
      env: ARCH=ppc64le LLVM_VERSION=10
      if: type = cron
    - name: "ARCH=x86_64 LLVM_VERSION=10"
      env: ARCH=x86_64 LLVM_VERSION=10
      if: type = cron
compiler: gcc
os: linux
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env LLVM_IAS=${LLVM_IAS} \
        --env REPO=${REPO} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/ubuntu:llvm${LLVM_VERSION:-11}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - ndesaulniers@google.com
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
    if: type = cron
