language: cpp
compiler: gcc
script: ./driver.sh
os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - binutils-aarch64-linux-gnu
      - qemu
      - expect-dev
cache:
  directories:
    buildroot/output/images
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
before_script:
  - curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install clang-8 -y
