language: cpp
matrix:
  include:
    - name: "ARCH=arm"
      env: ARCH=arm
    - name: "ARCH=arm64"
      env: ARCH=arm64
    - name: "ARCH=arm64 LD=ld.lld"
      env: ARCH=arm64 LD=ld.lld-8
    - name: "ARCH=x86_64"
      env: ARCH=x86_64
compiler: gcc
os: linux
dist: trusty
sudo: required
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - docker create -v ${TRAVIS_BUILD_DIR}:/travis --name travis debian
  - docker run --env ARCH=${ARCH} --env LD=${LD} --env CCACHE_DIR=/travis/.ccache --env CCACHE_COMPRESS=true --env CCACHE_COMPRESSLEVEL=9 --rm --volumes-from travis debian /bin/bash -c 'cd /travis && ./debian-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
