language: cpp
matrix:
  include:
    # linux
    - name: "ARCH=arm32_v5"
      env: ARCH=arm32_v5
    - name: "ARCH=arm32_v6"
      env: ARCH=arm32_v6
    - name: "ARCH=arm32_v7 LD=ld.lld"
      env: ARCH=arm32_v7 LD=ld.lld-9
    - name: "ARCH=arm64 LD=ld.lld"
      env: ARCH=arm64 LD=ld.lld-9
    - name: "ARCH=ppc32"
      env: ARCH=ppc32
    - name: "ARCH=ppc64le"
      env: ARCH=ppc64le
    - name: "ARCH=x86_64"
      env: ARCH=x86_64
    # linux (cron only)
    - name: "ARCH=arm32_v7"
      env: ARCH=arm32_v7
      if: type = cron
    - name: "ARCH=arm64"
      env: ARCH=arm64
      if: type = cron
    # linux-next (cron only)
    - name: "ARCH=arm32_v5 REPO=linux-next"
      env: ARCH=arm32_v5 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v6 REPO=linux-next"
      env: ARCH=arm32_v6 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=linux-next"
      env: ARCH=arm32_v7 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=linux-next"
      env: ARCH=arm32_v7 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm32_v7 LD=ld.lld REPO=linux-next"
      env: ARCH=arm32_v7 LD=ld.lld-9 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm64 REPO=linux-next"
      env: ARCH=arm64 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm64 LD=ld.lld REPO=linux-next"
      env: ARCH=arm64 LD=ld.lld-9 REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc32  REPO=linux-next"
      env: ARCH=ppc32 REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc64le  REPO=linux-next"
      env: ARCH=ppc64le REPO=linux-next
      if: type = cron
    - name: "ARCH=x86_64 REPO=linux-next"
      env: ARCH=x86_64 REPO=linux-next
      if: type = cron
    # stable
    - name: "ARCH=arm32_v7 REPO=4.19"
      env: ARCH=arm32_v7 REPO=4.19
      if: type = cron
    - name: "ARCH=arm64 REPO=4.19"
      env: ARCH=arm64 REPO=4.19
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.19"
      env: ARCH=ppc64le REPO=4.19
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.19"
      env: ARCH=x86_64 REPO=4.19
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.14"
      env: ARCH=arm32_v7 REPO=4.14
      if: type = cron
    - name: "ARCH=arm64 REPO=4.14"
      env: ARCH=arm64 REPO=4.14
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.14"
      env: ARCH=ppc64le REPO=4.14
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.14"
      env: ARCH=x86_64 REPO=4.14
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.9"
      env: ARCH=arm32_v7 REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.9"
      env: ARCH=arm64 REPO=4.9
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.9"
      env: ARCH=x86_64 REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.4"
      env: ARCH=arm64 REPO=4.4
      if: type = cron
    - name: "ARCH=x86_64 REPO=4.4"
      env: ARCH=x86_64 REPO=4.4
      if: type = cron
    # kernel/common
    - name: "ARCH=arm64 REPO=common-4.9"
      env: ARCH=arm64 REPO=common-4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=common-4.14"
      env: ARCH=arm64 REPO=common-4.14
      if: type = cron
    - name: "ARCH=arm64 REPO=common-4.19"
      env: ARCH=arm64 REPO=common-4.19
      if: type = cron
    - name: "ARCH=x86_64 REPO=common-4.9"
      env: ARCH=x86_64 REPO=common-4.9
      if: type = cron
    - name: "ARCH=x86_64 REPO=common-4.14"
      env: ARCH=x86_64 REPO=common-4.14
      if: type = cron
    - name: "ARCH=x86_64 REPO=common-4.19"
      env: ARCH=x86_64 REPO=common-4.19
      if: type = cron
    # linux with stable LLVM/Clang
    - name: "ARCH=arm32_v5 LLVM_VERSION=8"
      env: ARCH=arm32_v5 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=arm32_v6 LLVM_VERSION=8"
      env: ARCH=arm32_v6 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=arm32_v7 LLVM_VERSION=8"
      env: ARCH=arm32_v7 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=arm32_v7 LD=ld.lld LLVM_VERSION=8"
      env: ARCH=arm32_v7 LD=ld.lld-8 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=arm64 LLVM_VERSION=8"
      env: ARCH=arm64 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=arm64 LD=ld.lld LLVM_VERSION=8"
      env: ARCH=arm64 LD=ld.lld-8 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=ppc32 LLVM_VERSION=8"
      env: ARCH=ppc32 LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=ppc64le LLVM_VERSION=8"
      env: ARCH=ppc64le LLVM_VERSION=8
      if: type = cron
    - name: "ARCH=x86_64 LLVM_VERSION=8"
      env: ARCH=x86_64
      if: type = cron
compiler: gcc
os: linux
dist: trusty
sudo: required
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env REPO=${REPO} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/debian:llvm${LLVM_VERSION:-9}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - ndesaulniers@google.com
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
